import ast
import os

import pymongo

# Establish connection to MongoDB
client = pymongo.MongoClient(os.getenv("MONGODB_URI", "mongodb://localhost:27017/"))
db = client[os.getenv("MONGODB_DATABASE", "demo")]


def parse_find_query(find_query):
    """Parse a generated db.<collection>.find(filter, projection) command."""
    expression = ast.parse(find_query.strip(), mode="eval").body
    if (
        not isinstance(expression, ast.Call)
        or not isinstance(expression.func, ast.Attribute)
        or expression.func.attr != "find"
        or not isinstance(expression.func.value, ast.Attribute)
        or not isinstance(expression.func.value.value, ast.Name)
        or expression.func.value.value.id != "db"
        or expression.keywords
        or len(expression.args) not in (1, 2)
    ):
        raise ValueError(
            "Expected db.<collection>.find(filter) or "
            "db.<collection>.find(filter, projection)."
        )

    collection_name = expression.func.value.attr
    filter_query = ast.literal_eval(expression.args[0])
    projection_query = (
        ast.literal_eval(expression.args[1]) if len(expression.args) == 2 else None
    )

    if not isinstance(filter_query, dict):
        raise ValueError("The find filter must be a dictionary.")
    if projection_query is not None and not isinstance(projection_query, dict):
        raise ValueError("The find projection must be a dictionary.")

    return collection_name, filter_query, projection_query

# Function to execute MongoDB find command
def execute_find(find_query):
    try:
        collection_name, filter_query, projection_query = parse_find_query(find_query)
    except (SyntaxError, ValueError) as e:
        print(f"Error: Malformed find query. {e}")
        return

    # Execute the query
    collection = db[collection_name]
    try:
        if projection_query:
            result = collection.find(filter_query, projection_query)
        else:
            result = collection.find(filter_query)

        # Print the results
        for doc in result:
            print(doc)
    except Exception as e:
        print(f"Error executing query: {e}")

# Function to execute MongoDB aggregation command
def execute_aggregate(collection_name, pipeline):
    # The pipeline is now passed directly as a list, no need for string parsing
    collection = db[collection_name]
    try:
        result = collection.aggregate(pipeline)
        # Print the results
        for doc in result:
            print(doc)
    except Exception as e:
        print(f"Error executing aggregation pipeline: {e}")

# Sample usage
if __name__ == "__main__":
    # Example find query generated by Mongo_combined.py
    find_query = "db.usercuisine.find({'Rcuisine': {'$eq': 'American'}}, {'userID': 1, '_id': 0})"
    execute_find(find_query)

    # Example aggregation pipeline generated by MongoDB_Final.py
    aggregate_pipeline = [
        {"$match": {"Rcuisine": {"$eq": "American"}}},
        {"$project": {"userID": 1, "_id": 0}},
    ]
    execute_aggregate("usercuisine", aggregate_pipeline)
